### ISSUE TITLE
Can't run archival node with Docker

### ISSUE THREAD

**Issue by nazar-pc** [KILTprotocol/mashnet-node#278]
Using following docker-compose.yml:
```yml
version: '2'

services:
  kilt-spiritnet:
    image: kiltprotocol/mashnet-node:1.0.0
    ports:
      - 19953:9944 # ws port
    volumes:
      - ./kilt-spiritnet:/data
    command: [
      "--base-path", "/data",
      "--chain", "spiritnet",
      "--pruning", "archive",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors", "all",
    ]
```

Getting following error:
```
Error: Input("Error opening spec file: No such file or directory (os error 2)")
```

I don't understand why, according to source code this should have worked.
